#include <iostream>
using namespace std;
template <typename T>
T maximum(T a, T b);
int main()
{
    int a{23}, b{34};
    double c{34.4}, d{56.66};
    string e{"Hello"}, f{"World"};
    cout << "maximum(int) : " << maximum(a, b) << endl;
    cout << "maximum(double) : " << maximum(c, d) << endl;
    cout << "maximum(string) : " << maximum(e, f) << endl;
    return 0;
}
template <typename T>
T maximum(T a, T b)
{
    cout << "currently type is working " << endl;
    return (a > b) ? a : b;
}
/*

1. Functions templates are jsut blueprints. They are not c++ code consumed by the compiler. The compiler generates real c++ code by looking at the arguments you call your function template with

2. The real c++ function generated by the compiler is called template instance

3. A template instance will be reused when a similar function call(argument types) is issued. No duplicate are generated by the compiler.

*/
